task: nerf
gpus: [0]
exp_name: '2dgs'
scene: 'kitchen_mini'

# module path
train_dataset_module: lib.datasets.2dgs.dataset_colmap
test_dataset_module: lib.datasets.2dgs.dataset_colmap
network_module: lib.networks.gs.gs
loss_module: lib.train.losses.gs
evaluator_module: lib.evaluators.img_fit
visualizer_module: lib.visualizers.nerf

task_arg:
    N_rays: 128 # number of rays per training iteration
    chunk_size: 256 # chunkify
    white_bkgd: True # use white background
    cascade_samples: [64, 128] # importance sampling, you can set it to [64] for the initial implemetation

network:
    nerf:
        W: 256 # width
        D: 8 # depth
        V_D: 1 # appearance depth
    xyz_encoder:
        type: 'frequency' # positional encoding
        input_dim: 3
        freq: 10
    dir_encoder:
        type: 'frequency'
        input_dim: 3
        freq: 4

train_dataset:
    data_root: 'data/360v2'
    split: 'train'
    input_ratio: 1. # input image ratio, you can set it to 0.5 to acclerate training
    cams: [0, -1, 1] # input cameras, you can use this variable to select training images
    llffhold: 8
    load_iteration: 0
    shuffle: True
    resolution_scales: [1.0]
    resolution: 1 #Specifies resolution of the loaded images before training. 
                # If provided 1, 2, 4 or 8, uses original, 1/2, 1/4 or 1/8 resolution, respectively. 
    eval: True


test_dataset:
    data_root: 'data/360v2'
    split: 'test'
    input_ratio: 0.5
    cams: [0, -1, 100]
    llffhold: 8
    load_iteration: 0
    shuffle: False
    resolution_scales: [1.0]
    resolution: 1 #Specifies resolution of the loaded images before training. 
                # If provided 1, 2, 4 or 8, uses original, 1/2, 1/4 or 1/8 resolution, respectively. 




train:
    batch_size: 1
    lr: 5e-4
    weight_decay: 0.
    epoch: 400
    scheduler:
        type: 'exponential'
        gamma: 0.1
        decay_epochs: 1000
    num_workers: 4

test:
    batch_size: 1

ep_iter: 500
save_ep: 20
eval_ep: 20       # 10000 iterations
save_latest_ep: 5 # 2500 iterations
log_interval: 10
sh_degree: 3
eps: 0
resume: False